//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicRetro.SonLVL.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicRetro.SonLVL.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file selector is already being initialized..
        /// </summary>
        internal static string FileSelectorAlreadyBeingInitialized {
            get {
                return ResourceManager.GetString("FileSelectorAlreadyBeingInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file selector is not being initialized..
        /// </summary>
        internal static string FileSelectorNotBeingInitialized {
            get {
                return ResourceManager.GetString("FileSelectorNotBeingInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytecode/BR1Zone01.bin
        ///Bytecode/BR2Zone02.bin
        ///Bytecode/BR3Zone03.bin
        ///Bytecode/BR4Zone04.bin
        ///Bytecode/BR5Zone05.bin
        ///Bytecode/BR6Zone06.bin
        ///Bytecode/BR7Zone07.bin
        ///Bytecode/BR8Zone09.bin
        ///Bytecode/BR9Zone11.bin
        ///Bytecode/BR9Zone12.bin
        ///Bytecode/Continue.bin
        ///Bytecode/Credits.bin
        ///Bytecode/DLC_Zone01.bin
        ///Bytecode/DLC_Zone02.bin
        ///Bytecode/DLC_Zone06.bin
        ///Bytecode/DLC_Zone09.bin
        ///Bytecode/Ending.bin
        ///Bytecode/GlobalCode.bin
        ///Bytecode/LSelect.bin
        ///Bytecode/Mission_M.bin
        ///Bytecode/Mission_Zone01.bin
        ///Byteco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rsdk_files_list {
            get {
                return ResourceManager.GetString("rsdk_files_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnknownImg {
            get {
                object obj = ResourceManager.GetObject("UnknownImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
